In [1]:
%run Functions.ipynb
%run Data_Wrangling_2007.ipynb
%run Data_Wrangling_2006.ipynb
%run Data_Wrangling_2005.ipynb

..Loaded year 2007 quarter Q1
..Loaded year 2007 quarter Q2
..Loaded year 2007 quarter Q3
..Loaded year 2007 quarter Q4

The number of features is:
23

The number of observations is:
1246499

Frequency of Foreclosures
0    1143652
1     102847
Name: Foreclosed, dtype: int64

Percentage of Foreclosures
0    92
1     8
Name: Foreclosed, dtype: int32

         Harmonized Credit Score  Credit Score  Co-Borrower Credit Score
1213785                    794.0         794.0                     794.0
587882                     774.5         774.0                     775.0
1194659                    708.5         693.0                     724.0
175492                     628.0         628.0                       NaN
1143614                    787.5         785.0                     790.0
617838                     791.5         799.0                     784.0
386304                     779.5         779.0                     780.0
21969                      674.0         674.0                       NaN
86221                      475.0         475.0                       NaN
715353                     773.0         773.0                       NaN
..Loaded year 2006 quarter Q1
..Loaded year 2006 quarter Q2
..Loaded year 2006 quarter Q3
..Loaded year 2006 quarter Q4

..Loaded year 2002 quarter Q1
..Loaded year 2002 quarter Q2
..Loaded year 2002 quarter Q3
..Loaded year 2002 quarter Q4
Average change in 1 year: $ 64178.81
Average change in 5 years: $ 105136.67
Shape: (1240968, 26)
Shape: (1240968, 38)

,Loan ID,Origination Channel,Bank,Original Interest Rate,Original Mortgage Amount,Original Loan Term,Original Date,Original Combined Loan-to-Value (CLTV),Single Borrower,Original Debt to Income Ratio,First Time Home Buyer,Loan Purpose,Property Type,Occupancy Type,Property State,Zip Code,Mortgage Insurance %,Mortgage Insurance Type,File Year,File Quarter,Foreclosed,Month,Year,Harmonized Credit Score,Loan Change (1 Year),Loan Change (5 Years),Median Household Income,Region,Household Financial Obligations (Qtr),Household Financial Obligations (Yr),Consumer Debt Service Payment (Qtr),Consumer Debt Service Payment (Yr),National Home Price Index (Qtr),National Home Price Index (Yr),Mortgage Debt Service Payments (Qtr),Mortgage Debt Service Payments (Yr),Monthly Supply of Houses (Qtr),Monthly Supply of Houses (Yr)
1240963,289707303308,R,"BANK OF AMERICA, N.A.",6.125,417000,360,12/2007,72.0,0.0,24.0,N,0,SF,P,MA,17,0.0,NaN,2007,Q4,0,12,2007,739.5,11751.748252,61148.920562,65631.410714,Northeast,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923
1240964,872875680838,C,"BANK OF AMERICA, N.A.",6.625,72000,360,12/2007,90.0,1.0,43.0,Y,0,SF,P,IL,620,25.0,1.0,2007,Q4,0,12,2007,647.0,-675.262055,12114.312618,43661.963824,Midwest,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923
1240965,956920568298,B,"BANK OF AMERICA, N.A.",6.750,132000,360,12/2007,80.0,1.0,42.0,Y,0,SF,P,TX,770,0.0,NaN,2007,Q4,0,12,2007,618.0,12212.516586,14682.706767,56507.801980,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923
1240966,101372197983,R,"BANK OF AMERICA, N.A.",6.500,72000,360,12/2007,58.0,1.0,27.0,N,1,SF,P,TX,786,0.0,NaN,2007,Q4,0,12,2007,789.0,24079.145492,28195.118357,49856.781250,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923
1240967,151688999746,C,GMAC MORTGAGE,6.875,73000,360,12/2007,70.0,0.0,49.0,N,1,SF,P,NC,283,0.0,NaN,2007,Q4,0,12,2007,596.0,149800.000000,149800.000000,41527.179138,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923

Shape: (1240937, 46)

,Loan ID,Origination Channel,Bank,Original Interest Rate,Original Mortgage Amount,Original Loan Term,Original Date,Original Combined Loan-to-Value (CLTV),Single Borrower,Original Debt to Income Ratio,First Time Home Buyer,Loan Purpose,Property Type,Occupancy Type,Property State,Zip Code,Mortgage Insurance %,Mortgage Insurance Type,File Year,File Quarter,Foreclosed,Month,Year,Harmonized Credit Score,Loan Change (1 Year),Loan Change (5 Years),Median Household Income,Region,Household Financial Obligations (Qtr),Household Financial Obligations (Yr),Consumer Debt Service Payment (Qtr),Consumer Debt Service Payment (Yr),National Home Price Index (Qtr),National Home Price Index (Yr),Mortgage Debt Service Payments (Qtr),Mortgage Debt Service Payments (Yr),Monthly Supply of Houses (Qtr),Monthly Supply of Houses (Yr),Vacant Housing Units for Sale (Qtr),Vacant Housing Units for Sale (Yr),Homeownership Rate (Qtr),Homeownership Rate (Yr),Vacant Housing Units for Rent (Qtr),Vacant Housing Units for Rent (Yr),Rental Vacancy Rate (Qtr),Rental Vacancy Rate (Yr)
1240932,289707303308,R,"BANK OF AMERICA, N.A.",6.125,417000,360,12/2007,72.0,0.0,24.0,N,0,SF,P,MA,17,0.0,NaN,2007,Q4,0,12,2007,739.5,11751.748252,61148.920562,65631.410714,Northeast,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,0.103321,0.064057,-0.009202,-0.010720,-0.063291,0.040161,-0.070423,0.015385
1240933,872875680838,C,"BANK OF AMERICA, N.A.",6.625,72000,360,12/2007,90.0,1.0,43.0,Y,0,SF,P,IL,620,25.0,1.0,2007,Q4,0,12,2007,647.0,-675.262055,12114.312618,43661.963824,Midwest,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,0.224949,0.083183,-0.002782,-0.017808,-0.054110,-0.040127,-0.043103,-0.067227
1240934,956920568298,B,"BANK OF AMERICA, N.A.",6.750,132000,360,12/2007,80.0,1.0,42.0,Y,0,SF,P,TX,770,0.0,NaN,2007,Q4,0,12,2007,618.0,12212.516586,14682.706767,56507.801980,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,-0.057421,-0.034406,-0.001427,-0.011299,0.025015,0.030409,0.016529,-0.008065
1240935,101372197983,R,"BANK OF AMERICA, N.A.",6.500,72000,360,12/2007,58.0,1.0,27.0,N,1,SF,P,TX,786,0.0,NaN,2007,Q4,0,12,2007,789.0,24079.145492,28195.118357,49856.781250,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,-0.057421,-0.034406,-0.001427,-0.011299,0.025015,0.030409,0.016529,-0.008065
1240936,151688999746,C,GMAC MORTGAGE,6.875,73000,360,12/2007,70.0,0.0,49.0,N,1,SF,P,NC,283,0.0,NaN,2007,Q4,0,12,2007,596.0,149800.000000,149800.000000,41527.179138,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,-0.057421,-0.034406,-0.001427,-0.011299,0.025015,0.030409,0.016529,-0.008065

Shape: (1956, 6)

                                      numemp       asset     lnlsnet  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003        26.168  124.615732   85.632451
                       12/2004        26.419  130.989414   92.388641
                       12/2005        30.652  177.231290  127.509860
                       12/2006        30.878  182.588156  132.323277
                       12/2007        29.674  175.107526  131.028235

                                            liab         dep      eqtot
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003        114.734229   81.583566   9.881503
                       12/2004        121.085646   88.778793   9.903768
                       12/2005        158.965952  123.624623  18.265338
                       12/2006        163.258087  126.571181  19.330069
                       12/2007        155.453752  119.747933  19.653774

                                         numemp  asset (5 Yr)  asset (1 Yr)  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003        22.603893     -0.019142     -0.107483
                       12/2004        22.266027      0.012063     -0.035087
                       12/2005        25.190803      0.020493   3700.810308
                       12/2006        24.730582     -0.008982   2154.762843
                       12/2007        23.676434     -0.004417      0.580385

                                      lnlsnet (5 Yr)  lnlsnet (1 Yr)  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003             -0.034850       -0.134009
                       12/2004              0.020073       -0.088684
                       12/2005              0.023991     6358.795494
                       12/2006             -0.005436     3127.700127
                       12/2007             -0.004993        0.797541

                                      liab (5 Yr)  liab (1 Yr)  dep (5 Yr)  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003          -0.021955    -0.094721   -0.007901
                       12/2004           0.015482     0.004140    0.006817
                       12/2005           0.024525  3826.832756    0.044069
                       12/2006          -0.007996  2150.330007   -0.032849
                       12/2007          -0.006078     0.588613   -0.021850

                                       dep (1 Yr)  eqtot (5 Yr)  eqtot (1 Yr)
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003          -0.153465      0.015304     -0.232006
                       12/2004          -0.052278     -0.023072     -0.346685
                       12/2005        4212.787974     -0.013416   2663.572863
                       12/2006        3989.617678     -0.017415   2201.240374
                       12/2007           0.635273      0.009679      0.467293

Shape: (1240937, 57)

,Loan ID,Origination Channel,Bank,Original Interest Rate,Original Mortgage Amount,Original Loan Term,Original Date,Original Combined Loan-to-Value (CLTV),Single Borrower,Original Debt to Income Ratio,First Time Home Buyer,Loan Purpose,Property Type,Occupancy Type,Property State,Zip Code,Mortgage Insurance %,Mortgage Insurance Type,File Year,File Quarter,Foreclosed,Month,Year,Harmonized Credit Score,Loan Change (1 Year),Loan Change (5 Years),Median Household Income,Region,Household Financial Obligations (Qtr),Household Financial Obligations (Yr),Consumer Debt Service Payment (Qtr),Consumer Debt Service Payment (Yr),National Home Price Index (Qtr),National Home Price Index (Yr),Mortgage Debt Service Payments (Qtr),Mortgage Debt Service Payments (Yr),Monthly Supply of Houses (Qtr),Monthly Supply of Houses (Yr),Vacant Housing Units for Sale (Qtr),Vacant Housing Units for Sale (Yr),Homeownership Rate (Qtr),Homeownership Rate (Yr),Vacant Housing Units for Rent (Qtr),Vacant Housing Units for Rent (Yr),Rental Vacancy Rate (Qtr),Rental Vacancy Rate (Yr),numemp,asset (5 Yr),asset (1 Yr),lnlsnet (5 Yr),lnlsnet (1 Yr),liab (5 Yr),liab (1 Yr),dep (5 Yr),dep (1 Yr),eqtot (5 Yr),eqtot (1 Yr)
1240932,289707303308,R,"BANK OF AMERICA, N.A.",6.125,417000,360,12/2007,72.0,0.0,24.0,N,0,SF,P,MA,17,0.0,NaN,2007,Q4,0,12,2007,739.5,11751.748252,61148.920562,65631.410714,Northeast,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,0.103321,0.064057,-0.009202,-0.010720,-0.063291,0.040161,-0.070423,0.015385,125.632549,-0.011179,1.557514,-0.012883,0.999584,-0.010905,1.630292,-0.000934,1.315701,-0.017122,0.929907
1240933,872875680838,C,"BANK OF AMERICA, N.A.",6.625,72000,360,12/2007,90.0,1.0,43.0,Y,0,SF,P,IL,620,25.0,1.0,2007,Q4,0,12,2007,647.0,-675.262055,12114.312618,43661.963824,Midwest,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,0.224949,0.083183,-0.002782,-0.017808,-0.054110,-0.040127,-0.043103,-0.067227,125.632549,-0.011179,1.557514,-0.012883,0.999584,-0.010905,1.630292,-0.000934,1.315701,-0.017122,0.929907
1240934,956920568298,B,"BANK OF AMERICA, N.A.",6.750,132000,360,12/2007,80.0,1.0,42.0,Y,0,SF,P,TX,770,0.0,NaN,2007,Q4,0,12,2007,618.0,12212.516586,14682.706767,56507.801980,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,-0.057421,-0.034406,-0.001427,-0.011299,0.025015,0.030409,0.016529,-0.008065,125.632549,-0.011179,1.557514,-0.012883,0.999584,-0.010905,1.630292,-0.000934,1.315701,-0.017122,0.929907
1240935,101372197983,R,"BANK OF AMERICA, N.A.",6.500,72000,360,12/2007,58.0,1.0,27.0,N,1,SF,P,TX,786,0.0,NaN,2007,Q4,0,12,2007,789.0,24079.145492,28195.118357,49856.781250,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,-0.057421,-0.034406,-0.001427,-0.011299,0.025015,0.030409,0.016529,-0.008065,125.632549,-0.011179,1.557514,-0.012883,0.999584,-0.010905,1.630292,-0.000934,1.315701,-0.017122,0.929907
1240936,151688999746,C,GMAC MORTGAGE,6.875,73000,360,12/2007,70.0,0.0,49.0,N,1,SF,P,NC,283,0.0,NaN,2007,Q4,0,12,2007,596.0,149800.000000,149800.000000,41527.179138,South,0.008014,0.026461,0.005504,0.015049,-0.038276,-0.05398,0.014897,0.036944,0.043478,0.476923,-0.057421,-0.034406,-0.001427,-0.011299,0.025015,0.030409,0.016529,-0.008065,0.409315,0.259873,6.508684,0.223299,5.455538,0.246660,6.332854,0.291450,7.469388,0.371031,8.275430

Loan ID                                    0.00
Origination Channel                        0.00
Bank                                       0.00
Original Interest Rate                     0.00
Original Mortgage Amount                   0.00
Original Loan Term                         0.00
Original Date                              0.00
Original Combined Loan-to-Value (CLTV)     0.00
Single Borrower                            0.00
Original Debt to Income Ratio              2.75
First Time Home Buyer                      0.00
Loan Purpose                               0.00
Property Type                              0.00
Occupancy Type                             0.00
Property State                             0.00
Zip Code                                   0.00
Mortgage Insurance %                       0.00
Mortgage Insurance Type                   82.62
File Year                                  0.00
File Quarter                               0.00
Foreclosed                                 0.00
Month                                      0.00
Year                                       0.00
Harmonized Credit Score                    0.19
Loan Change (1 Year)                       0.00
Loan Change (5 Years)                      0.00
Median Household Income                    0.00
Region                                     0.00
Household Financial Obligations (Qtr)      0.00
Household Financial Obligations (Yr)       0.00
Consumer Debt Service Payment (Qtr)        0.00
Consumer Debt Service Payment (Yr)         0.00
National Home Price Index (Qtr)            0.00
National Home Price Index (Yr)             0.00
Mortgage Debt Service Payments (Qtr)       0.00
Mortgage Debt Service Payments (Yr)        0.00
Monthly Supply of Houses (Qtr)             0.00
Monthly Supply of Houses (Yr)              0.00
Vacant Housing Units for Sale (Qtr)        0.00
Vacant Housing Units for Sale (Yr)         0.00
Homeownership Rate (Qtr)                   0.00
Homeownership Rate (Yr)                    0.00
Vacant Housing Units for Rent (Qtr)        0.00
Vacant Housing Units for Rent (Yr)         0.00
Rental Vacancy Rate (Qtr)                  0.00
Rental Vacancy Rate (Yr)                   0.00
numemp                                     1.22
asset (5 Yr)                               1.22
asset (1 Yr)                               1.22
lnlsnet (5 Yr)                             1.22
lnlsnet (1 Yr)                             1.22
liab (5 Yr)                                1.22
liab (1 Yr)                                1.22
dep (5 Yr)                                 1.22
dep (1 Yr)                                 1.22
eqtot (5 Yr)                               1.22
eqtot (1 Yr)                               1.22
dtype: float64
..Loaded year 2006 quarter Q1
..Loaded year 2006 quarter Q2
..Loaded year 2006 quarter Q3
..Loaded year 2006 quarter Q4

The number of features is:
23

The number of observations is:
1096598

Frequency of Foreclosures
0    1014644
1      81954
Name: Foreclosed, dtype: int64

Percentage of Foreclosures
0    93
1     7
Name: Foreclosed, dtype: int32

         Harmonized Credit Score  Credit Score  Co-Borrower Credit Score
639903                     742.5         713.0                     772.0
759103                     799.0         795.0                     803.0
570914                     800.0         800.0                       NaN
904721                     747.0         702.0                     792.0
1040180                    774.0         774.0                       NaN
1076765                    644.0         644.0                       NaN
655780                     793.5         813.0                     774.0
595291                     807.0         807.0                       NaN
901325                     706.5         759.0                     654.0
739303                     626.0         626.0                       NaN
..Loaded year 2005 quarter Q1
..Loaded year 2005 quarter Q2
..Loaded year 2005 quarter Q3
..Loaded year 2005 quarter Q4

..Loaded year 2001 quarter Q1
..Loaded year 2001 quarter Q2
..Loaded year 2001 quarter Q3
..Loaded year 2001 quarter Q4
Average change in 1 year: $ 79663.33
Average change in 5 years: $ 105300.21
Shape: (1091805, 26)
Shape: (1091805, 38)

,Loan ID,Origination Channel,Bank,Original Interest Rate,Original Mortgage Amount,Original Loan Term,Original Date,Original Combined Loan-to-Value (CLTV),Single Borrower,Original Debt to Income Ratio,First Time Home Buyer,Loan Purpose,Property Type,Occupancy Type,Property State,Zip Code,Mortgage Insurance %,Mortgage Insurance Type,File Year,File Quarter,Foreclosed,Month,Year,Harmonized Credit Score,Loan Change (1 Year),Loan Change (5 Years),Median Household Income,Region,Household Financial Obligations (Qtr),Household Financial Obligations (Yr),Consumer Debt Service Payment (Qtr),Consumer Debt Service Payment (Yr),National Home Price Index (Qtr),National Home Price Index (Yr),Mortgage Debt Service Payments (Qtr),Mortgage Debt Service Payments (Yr),Monthly Supply of Houses (Qtr),Monthly Supply of Houses (Yr)
1091800,859727916857,R,OTHER,6.125,224000,360,12/2006,95.0,0.0,45.0,N,0,SF,P,OK,740,25.0,1,2006,Q4,0,12,2006,655.5,10134.523467,38036.751764,41502.890110,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531
1091801,509420140308,R,OTHER,6.500,90000,360,12/2006,79.0,0.0,43.0,N,0,SF,P,MO,641,0.0,0,2006,Q4,0,12,2006,650.0,-6375.362319,13427.831094,37282.507443,Midwest,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531
1091802,430164070754,R,OTHER,7.750,100000,360,12/2006,56.0,1.0,45.0,N,1,CO,I,FL,331,0.0,0,2006,Q4,0,12,2006,603.0,21803.446771,73953.516409,41293.262500,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531
1091803,397118404553,B,FIRST TENNESSEE BANK NATIONAL ASSOCIATION,6.750,74000,360,12/2006,73.0,1.0,32.0,N,1,SF,P,VA,245,0.0,0,2006,Q4,0,12,2006,626.0,-34500.000000,-23500.000000,40097.544601,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531
1091804,494482357959,R,FIRST TENNESSEE BANK NATIONAL ASSOCIATION,6.375,98000,360,12/2006,55.0,0.0,34.0,N,1,SF,I,NC,287,0.0,0,2006,Q4,0,12,2006,752.5,14041.666667,72333.333333,37811.193925,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531

Shape: (1091746, 46)

,Loan ID,Origination Channel,Bank,Original Interest Rate,Original Mortgage Amount,Original Loan Term,Original Date,Original Combined Loan-to-Value (CLTV),Single Borrower,Original Debt to Income Ratio,First Time Home Buyer,Loan Purpose,Property Type,Occupancy Type,Property State,Zip Code,Mortgage Insurance %,Mortgage Insurance Type,File Year,File Quarter,Foreclosed,Month,Year,Harmonized Credit Score,Loan Change (1 Year),Loan Change (5 Years),Median Household Income,Region,Household Financial Obligations (Qtr),Household Financial Obligations (Yr),Consumer Debt Service Payment (Qtr),Consumer Debt Service Payment (Yr),National Home Price Index (Qtr),National Home Price Index (Yr),Mortgage Debt Service Payments (Qtr),Mortgage Debt Service Payments (Yr),Monthly Supply of Houses (Qtr),Monthly Supply of Houses (Yr),Vacant Housing Units for Sale (Qtr),Vacant Housing Units for Sale (Yr),Homeownership Rate (Qtr),Homeownership Rate (Yr),Vacant Housing Units for Rent (Qtr),Vacant Housing Units for Rent (Yr),Rental Vacancy Rate (Qtr),Rental Vacancy Rate (Yr)
1091741,859727916857,R,OTHER,6.125,224000,360,12/2006,95.0,0.0,45.0,N,0,SF,P,OK,740,25.0,1,2006,Q4,0,12,2006,655.5,10134.523467,38036.751764,41502.890110,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719
1091742,509420140308,R,OTHER,6.500,90000,360,12/2006,79.0,0.0,43.0,N,0,SF,P,MO,641,0.0,0,2006,Q4,0,12,2006,650.0,-6375.362319,13427.831094,37282.507443,Midwest,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.073786,0.196970,0.002747,0.002747,-0.063304,-0.034659,-0.055556,-0.032520
1091743,430164070754,R,OTHER,7.750,100000,360,12/2006,56.0,1.0,45.0,N,1,CO,I,FL,331,0.0,0,2006,Q4,0,12,2006,603.0,21803.446771,73953.516409,41293.262500,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719
1091744,397118404553,B,FIRST TENNESSEE BANK NATIONAL ASSOCIATION,6.750,74000,360,12/2006,73.0,1.0,32.0,N,1,SF,P,VA,245,0.0,0,2006,Q4,0,12,2006,626.0,-34500.000000,-23500.000000,40097.544601,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719
1091745,494482357959,R,FIRST TENNESSEE BANK NATIONAL ASSOCIATION,6.375,98000,360,12/2006,55.0,0.0,34.0,N,1,SF,I,NC,287,0.0,0,2006,Q4,0,12,2006,752.5,14041.666667,72333.333333,37811.193925,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719

Shape: (1956, 6)

                                      numemp       asset     lnlsnet  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003        26.168  124.615732   85.632451
                       12/2004        26.419  130.989414   92.388641
                       12/2005        30.652  177.231290  127.509860
                       12/2006        30.878  182.588156  132.323277
                       12/2007        29.674  175.107526  131.028235

                                            liab         dep      eqtot
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003        114.734229   81.583566   9.881503
                       12/2004        121.085646   88.778793   9.903768
                       12/2005        158.965952  123.624623  18.265338
                       12/2006        163.258087  126.571181  19.330069
                       12/2007        155.453752  119.747933  19.653774

                                         numemp  asset (5 Yr)  asset (1 Yr)  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003        22.603893     -0.019142     -0.107483
                       12/2004        22.266027      0.012063     -0.035087
                       12/2005        25.190803      0.020493   3700.810308
                       12/2006        24.730582     -0.008982   2154.762843
                       12/2007        23.676434     -0.004417      0.580385

                                      lnlsnet (5 Yr)  lnlsnet (1 Yr)  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003             -0.034850       -0.134009
                       12/2004              0.020073       -0.088684
                       12/2005              0.023991     6358.795494
                       12/2006             -0.005436     3127.700127
                       12/2007             -0.004993        0.797541

                                      liab (5 Yr)  liab (1 Yr)  dep (5 Yr)  \
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003          -0.021955    -0.094721   -0.007901
                       12/2004           0.015482     0.004140    0.006817
                       12/2005           0.024525  3826.832756    0.044069
                       12/2006          -0.007996  2150.330007   -0.032849
                       12/2007          -0.006078     0.588613   -0.021850

                                       dep (1 Yr)  eqtot (5 Yr)  eqtot (1 Yr)
Bank                   Original Date
SUNTRUST MORTGAGE INC. 12/2003          -0.153465      0.015304     -0.232006
                       12/2004          -0.052278     -0.023072     -0.346685
                       12/2005        4212.787974     -0.013416   2663.572863
                       12/2006        3989.617678     -0.017415   2201.240374
                       12/2007           0.635273      0.009679      0.467293

Shape: (1091746, 57)

,Loan ID,Origination Channel,Bank,Original Interest Rate,Original Mortgage Amount,Original Loan Term,Original Date,Original Combined Loan-to-Value (CLTV),Single Borrower,Original Debt to Income Ratio,First Time Home Buyer,Loan Purpose,Property Type,Occupancy Type,Property State,Zip Code,Mortgage Insurance %,Mortgage Insurance Type,File Year,File Quarter,Foreclosed,Month,Year,Harmonized Credit Score,Loan Change (1 Year),Loan Change (5 Years),Median Household Income,Region,Household Financial Obligations (Qtr),Household Financial Obligations (Yr),Consumer Debt Service Payment (Qtr),Consumer Debt Service Payment (Yr),National Home Price Index (Qtr),National Home Price Index (Yr),Mortgage Debt Service Payments (Qtr),Mortgage Debt Service Payments (Yr),Monthly Supply of Houses (Qtr),Monthly Supply of Houses (Yr),Vacant Housing Units for Sale (Qtr),Vacant Housing Units for Sale (Yr),Homeownership Rate (Qtr),Homeownership Rate (Yr),Vacant Housing Units for Rent (Qtr),Vacant Housing Units for Rent (Yr),Rental Vacancy Rate (Qtr),Rental Vacancy Rate (Yr),numemp,asset (5 Yr),asset (1 Yr),lnlsnet (5 Yr),lnlsnet (1 Yr),liab (5 Yr),liab (1 Yr),dep (5 Yr),dep (1 Yr),eqtot (5 Yr),eqtot (1 Yr)
1091741,859727916857,R,OTHER,6.125,224000,360,12/2006,95.0,0.0,45.0,N,0,SF,P,OK,740,25.0,1,2006,Q4,0,12,2006,655.5,10134.523467,38036.751764,41502.890110,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719,1146.556978,0.014966,-0.290966,0.016308,-0.227339,0.012447,-0.298796,-0.007743,-0.269225,0.034050,-0.223513
1091742,509420140308,R,OTHER,6.500,90000,360,12/2006,79.0,0.0,43.0,N,0,SF,P,MO,641,0.0,0,2006,Q4,0,12,2006,650.0,-6375.362319,13427.831094,37282.507443,Midwest,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.073786,0.196970,0.002747,0.002747,-0.063304,-0.034659,-0.055556,-0.032520,1146.556978,0.014966,-0.290966,0.016308,-0.227339,0.012447,-0.298796,-0.007743,-0.269225,0.034050,-0.223513
1091743,430164070754,R,OTHER,7.750,100000,360,12/2006,56.0,1.0,45.0,N,1,CO,I,FL,331,0.0,0,2006,Q4,0,12,2006,603.0,21803.446771,73953.516409,41293.262500,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719,1146.556978,0.014966,-0.290966,0.016308,-0.227339,0.012447,-0.298796,-0.007743,-0.269225,0.034050,-0.223513
1091744,397118404553,B,FIRST TENNESSEE BANK NATIONAL ASSOCIATION,6.750,74000,360,12/2006,73.0,1.0,32.0,N,1,SF,P,VA,245,0.0,0,2006,Q4,0,12,2006,626.0,-34500.000000,-23500.000000,40097.544601,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719,9.653401,-0.063177,0.578432,-0.000679,0.599060,-0.065098,0.607246,-0.225741,0.271785,-0.035841,0.360762
1091745,494482357959,R,FIRST TENNESSEE BANK NATIONAL ASSOCIATION,6.375,98000,360,12/2006,55.0,0.0,34.0,N,1,SF,I,NC,287,0.0,0,2006,Q4,0,12,2006,752.5,14041.666667,72333.333333,37811.193925,South,0.008024,0.023268,-0.002505,-0.030116,-0.006377,0.017328,0.014117,0.071238,-0.029851,0.326531,0.080336,0.412226,0.002833,-0.004219,0.045872,0.122047,0.042017,0.087719,9.653401,-0.063177,0.578432,-0.000679,0.599060,-0.065098,0.607246,-0.225741,0.271785,-0.035841,0.360762

Loan ID                                   0.00
Origination Channel                       0.00
Bank                                      0.00
Original Interest Rate                    0.00
Original Mortgage Amount                  0.00
Original Loan Term                        0.00
Original Date                             0.00
Original Combined Loan-to-Value (CLTV)    0.00
Single Borrower                           0.00
Original Debt to Income Ratio             2.85
First Time Home Buyer                     0.00
Loan Purpose                              0.00
Property Type                             0.00
Occupancy Type                            0.00
Property State                            0.00
Zip Code                                  0.00
Mortgage Insurance %                      0.00
Mortgage Insurance Type                   0.00
File Year                                 0.00
File Quarter                              0.00
Foreclosed                                0.00
Month                                     0.00
Year                                      0.00
Harmonized Credit Score                   0.41
Loan Change (1 Year)                      0.00
Loan Change (5 Years)                     0.00
Median Household Income                   0.01
Region                                    0.00
Household Financial Obligations (Qtr)     0.00
Household Financial Obligations (Yr)      0.00
Consumer Debt Service Payment (Qtr)       0.00
Consumer Debt Service Payment (Yr)        0.00
National Home Price Index (Qtr)           0.00
National Home Price Index (Yr)            0.00
Mortgage Debt Service Payments (Qtr)      0.00
Mortgage Debt Service Payments (Yr)       0.00
Monthly Supply of Houses (Qtr)            0.00
Monthly Supply of Houses (Yr)             0.00
Vacant Housing Units for Sale (Qtr)       0.00
Vacant Housing Units for Sale (Yr)        0.00
Homeownership Rate (Qtr)                  0.00
Homeownership Rate (Yr)                   0.00
Vacant Housing Units for Rent (Qtr)       0.00
Vacant Housing Units for Rent (Yr)        0.00
Rental Vacancy Rate (Qtr)                 0.00
Rental Vacancy Rate (Yr)                  0.00
numemp                                    3.51
asset (5 Yr)                              3.51
asset (1 Yr)                              3.51
lnlsnet (5 Yr)                            3.51
lnlsnet (1 Yr)                            3.51
liab (5 Yr)                               3.51
liab (1 Yr)                               3.51
dep (5 Yr)                                3.51
dep (1 Yr)                                3.51
eqtot (5 Yr)                              3.51
eqtot (1 Yr)                              3.51
dtype: float64
(1091746, 57)
(1240937, 57)
..Loaded year 2005 quarter Q1
..Loaded year 2005 quarter Q2
..Loaded year 2005 quarter Q3

MemoryError: Unable to allocate array with shape (13, 84145357) and data type object